/* universal include header file */
/********************************
/* author				: BS Prashanth
/* date created : 30/12/2014
*********************************/

#ifndef INCLUDES_H
#define INCLUDES_H

#include <AT89X52.h>
#include <string.h>
#include <stdlib.h>
#include "types.h"
#include "const.h"
#include "delay.h"
#include "buz.h"
#include "lcd.h"
#include "uart.h"
#include "led.h"
#include "gsm.h"
#include "gps.h"
#include "i2c.h"
#include "ADC.h"
#include "mkb.h"
#include "fp.h"

#endif
/* end of File */
